### ISSUE TITLE
Allow optionally specifying custom DB_FILE_PATH

### ISSUE THREAD

**Issue by jpadilla** [gcollazo/sqlogs#1]
API Ideas:

```
const log = require('sqlogs')('logs/db.sqlite');
```

```
const log = require('sqlogs');
log.configure({ path: 'logs/db.sqlite' });
```

**Comment by gcollazo** [comment]
Decided to go a different route in terms of API to prevent a breaking change.

**The current API will remain unchanged** and it will keep using the default `./sqlogs.sqlite` path. If a user wants to change the file path they will have to require from `sqlogs/advanced` and use the `createLogger` factory to create a customized log function.

```js
const { createLogger } = require('sqlogs/advanced');
const log = createLogger({ path: './custom.sqlite' });
```

I still have to do some clean up and after that I release an updated version to npm. Thanks for the feedback.

**Comment by gcollazo** [comment]
@jpadilla actually went with something a litter different and more explicit.

```js
const { createLogger, createSqliteTransport } = require('sqlogs/advanced');
const log = createLogger(createSqliteTransport({ path: './custom.sqlite' }));
```
